export const TODO_GET_PROCESS_START = 'TODO_GET_PROCESS_START';
export const TODO_GET_PROCESS_SUCCESS = 'TODO_GET_PROCESS_SUCCESS';
export const TODO_GET_PROCESS_ERROR = 'TODO_GET_PROCESS_ERROR';

export const TODO_SAVE_PROCESS_START = 'TODO_SAVE_PROCESS_START';
export const TODO_SAVE_PROCESS_SUCCESS = 'TODO_SAVE_PROCESS_SUCCESS';
export const TODO_SAVE_PROCESS_ERROR = 'TODO_SAVE_PROCESS_ERROR';

export const TODO_DELETE_PROCESS_START = 'TODO_DELETE_PROCESS_START';
export const TODO_DELETE_PROCESS_SUCCESS = 'TODO_DELETE_PROCESS_SUCCESS';
export const TODO_DELETE_PROCESS_ERROR = 'TODO_DELETE_PROCESS_ERROR';
